
# Configures ChessEngine tests at Travis CI (https://travis-ci.org).

language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y build-essential
 - sudo apt-get install -y pkg-config
 - sudo apt-get install -y cmake
 - sudo apt-get install -y check
 - sudo apt-get install -y libglib2.0-dev

install: false

script:
 - cmake .
 - make
 - ctest -V
